services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  myapp:
    build:
      context: myapp
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
    ports:
      - "8000:6006"
    volumes:
      - media:/media

  messaging:
    build:
      context: messaging
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      WAIT_HOSTS: myapp:6006
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    volumes:
      - media:/media
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      WAIT_HOSTS: postgres:5432
    ports:
      - "5050:80"
volumes:
  media:
